### PR TITLE
Added coverage file to report code coverage

### PR DESCRIPTION
**Pull request by matthewfcarlson**

### CODE REVIEW

**Comment by matthewfcarlson** [comment]
This may or may not work

**Comment by matthewfcarlson** [comment]
https://github.com/MicrosoftDocs/codecoverage-yaml-samples
https://docs.microsoft.com/en-us/azure/devops/pipelines/test/codecoverage-for-pullrequests?view=azure-devops#coverage-status-details-and-indicators

**Comment by spbrogan** [comment]
in the docs there are a lot of limitations.  Azure repos and .coverage files only.  We don't do either of those so do you think this will work?

**Comment by matthewfcarlson** [comment]
This doesn't work. We'll need to go with something codecov.io

**Pull request closed without merging**
