### PR TITLE
Stop buildreport_parser.py from attempting to search for binary compo…

### PR DESCRIPTION
**Pull request by edwinzMSFT**
…nents in module list.

### CODE REVIEW

**Review by spbrogan — CHANGES_REQUESTED** [review]
lets find a better and more sustainable way to fix the path issues.

**Comment by Javagedes** [comment]
@edwinzMSFT is this PR in regard to the sporadic failing of build_report described in #152 ? If so, I've explained the issue there. I've submitted #153 that will catch the incorrect package path at build rather then causing a failure down the line in build_report.

**Comment by edwinzMSFT** [comment]
Nested package path check is a better way of fixing this: https://github.com/tianocore/edk2-pytool-library/pull/153

**Comment by edwinzMSFT** [comment]
> @edwinzMSFT is this PR in regard to the sporadic failing of build_report described in #152 ? If so, I've explained the issue there. I've submitted #153 that will catch the incorrect package path at build rather then causing a failure down the line in build_report.

Yep, I've went ahead and closed this one.

**Pull request closed without merging**
